// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: proxy/masque/config.proto

package masque

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Cloudflare WARP over MASQUE (HTTP/3 CONNECT-IP).
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Base64 DER of the device's P-256 key (SEC1 or PKCS#8), enrolled on the WARP account.
	PrivateKey string `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	// PEM of the endpoint's P-256 public key, from the account's peer config. Pins the server.
	EndpointPublicKey string `protobuf:"bytes,2,opt,name=endpoint_public_key,json=endpointPublicKey,proto3" json:"endpoint_public_key,omitempty"`
	// host:port of the MASQUE endpoint (UDP).
	Endpoint string `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// TLS server name; defaults to consumer-masque.cloudflareclient.com.
	Sni string `protobuf:"bytes,4,opt,name=sni,proto3" json:"sni,omitempty"`
	// Tunnel addresses assigned to the account (IPv4 and/or IPv6, no prefix).
	Addresses []string `protobuf:"bytes,5,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Mtu       int32    `protobuf:"varint,6,opt,name=mtu,proto3" json:"mtu,omitempty"`
	// Resolvers used inside the tunnel for domain targets.
	Dns           []string `protobuf:"bytes,7,rep,name=dns,proto3" json:"dns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_proxy_masque_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_masque_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_proxy_masque_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *Config) GetEndpointPublicKey() string {
	if x != nil {
		return x.EndpointPublicKey
	}
	return ""
}

func (x *Config) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Config) GetSni() string {
	if x != nil {
		return x.Sni
	}
	return ""
}

func (x *Config) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *Config) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *Config) GetDns() []string {
	if x != nil {
		return x.Dns
	}
	return nil
}

var File_proxy_masque_config_proto protoreflect.FileDescriptor

const file_proxy_masque_config_proto_rawDesc = "" +
	"\n" +
	"\x19proxy/masque/config.proto\x12\x11xray.proxy.masque\"\xc9\x01\n" +
	"\x06Config\x12\x1f\n" +
	"\vprivate_key\x18\x01 \x01(\tR\n" +
	"privateKey\x12.\n" +
	"\x13endpoint_public_key\x18\x02 \x01(\tR\x11endpointPublicKey\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x10\n" +
	"\x03sni\x18\x04 \x01(\tR\x03sni\x12\x1c\n" +
	"\taddresses\x18\x05 \x03(\tR\taddresses\x12\x10\n" +
	"\x03mtu\x18\x06 \x01(\x05R\x03mtu\x12\x10\n" +
	"\x03dns\x18\a \x03(\tR\x03dnsBU\n" +
	"\x15com.xray.proxy.masqueP\x01Z&github.com/xtls/xray-core/proxy/masque\xaa\x02\x11Xray.Proxy.Masqueb\x06proto3"

var (
	file_proxy_masque_config_proto_rawDescOnce sync.Once
	file_proxy_masque_config_proto_rawDescData []byte
)

func file_proxy_masque_config_proto_rawDescGZIP() []byte {
	file_proxy_masque_config_proto_rawDescOnce.Do(func() {
		file_proxy_masque_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_masque_config_proto_rawDesc), len(file_proxy_masque_config_proto_rawDesc)))
	})
	return file_proxy_masque_config_proto_rawDescData
}

var file_proxy_masque_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proxy_masque_config_proto_goTypes = []any{
	(*Config)(nil), // 0: xray.proxy.masque.Config
}
var file_proxy_masque_config_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proxy_masque_config_proto_init() }
func file_proxy_masque_config_proto_init() {
	if File_proxy_masque_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_masque_config_proto_rawDesc), len(file_proxy_masque_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_masque_config_proto_goTypes,
		DependencyIndexes: file_proxy_masque_config_proto_depIdxs,
		MessageInfos:      file_proxy_masque_config_proto_msgTypes,
	}.Build()
	File_proxy_masque_config_proto = out.File
	file_proxy_masque_config_proto_goTypes = nil
	file_proxy_masque_config_proto_depIdxs = nil
}
